"""Constants for Adaptive Pergola."""

from homeassistant.const import Platform

DOMAIN = "adaptive_pergola"
MANUFACTURER = "Adaptive Pergola"
SUN_ENTITY_ID = "sun.sun"

PLATFORMS = [
    Platform.SENSOR,
    Platform.SWITCH,
    Platform.BUTTON,
    Platform.SELECT,
    Platform.BINARY_SENSOR,
]

TRACKING_MAX_LIGHT = "max_light"
TRACKING_MAX_SHADE = "max_shade"
TRACKING_BALANCED = "balanced"

TRACKING_STRATEGIES = [
    TRACKING_MAX_LIGHT,
    TRACKING_MAX_SHADE,
    TRACKING_BALANCED,
]

ACTUATOR_MODE_COVER_TILT = "cover_tilt_percentage"
ACTUATOR_MODE_COVER_POSITION = "cover_position_percentage"
ACTUATOR_MODE_NUMBER_ANGLE = "number_angle_degrees"
ACTUATOR_MODE_NUMBER_PERCENT = "number_actuator_percentage"
ACTUATOR_MODE_NUMBER_CUSTOM = "number_custom_range"

ACTUATOR_MODES = [
    ACTUATOR_MODE_COVER_TILT,
    ACTUATOR_MODE_COVER_POSITION,
    ACTUATOR_MODE_NUMBER_ANGLE,
    ACTUATOR_MODE_NUMBER_PERCENT,
    ACTUATOR_MODE_NUMBER_CUSTOM,
]

CONF_NAME = "name"
CONF_TARGET_ENTITY = "target_entity"
CONF_COMMAND_MODE = "command_mode"
CONF_COMMAND_VALUE_MIN = "command_value_min"
CONF_COMMAND_VALUE_MAX = "command_value_max"
CONF_AUTOMATIC_CONTROL = "automatic_control"
CONF_AUTO_APPLY = "auto_apply"
CONF_MANUAL_OVERRIDE_DURATION = "manual_override_duration"
CONF_MANUAL_OVERRIDE_RESET = "manual_override_reset"
CONF_MANUAL_THRESHOLD = "manual_threshold"
CONF_MANUAL_IGNORE_INTERMEDIATE = "manual_ignore_intermediate"
CONF_TRACKING_MODE = "tracking_mode"

CONF_SLAT_WIDTH_M = "slat_width_m"
CONF_SLAT_THICKNESS_M = "slat_thickness_m"
CONF_SLAT_AXIS_SPACING_M = "slat_axis_spacing_m"
CONF_SLAT_AXIS_HEIGHT_M = "slat_axis_height_m"
CONF_PERGOLA_LENGTH_M = "pergola_length_m"
CONF_PERGOLA_WIDTH_M = "pergola_width_m"
CONF_AXIS_AZIMUTH_DEG = "axis_azimuth_deg"
CONF_SLAT_AXIS_AZIMUTH_DEG = "slat_axis_azimuth_deg"
CONF_PERGOLA_ORIENTATION_AZIMUTH_DEG = "pergola_orientation_azimuth_deg"
CONF_OPENING_AZIMUTH_DEG = "opening_azimuth_deg"

CONF_CLOSED_ANGLE_DEG = "closed_angle_deg"
CONF_OPEN_ANGLE_DEG = "open_angle_deg"
CONF_OPEN_ACTUATOR_PERCENT = "open_actuator_percent"
CONF_MAX_TRAVEL_ANGLE_DEG = "max_travel_angle_deg"
CONF_CLOSES_AGAIN_AFTER_OPEN = "closes_again_after_open"

CONF_HAS_HOUSE_ATTACHMENT = "has_house_attachment"
CONF_HOUSE_HEIGHT_M = "house_height_m"
CONF_HOUSE_EXTENDS_LEFT_M = "house_extends_left_m"
CONF_HOUSE_EXTENDS_RIGHT_M = "house_extends_right_m"

CONF_HAS_ADDITIONAL_PROTECTED_AREA = "has_additional_protected_area"
CONF_ADDITIONAL_PROTECTED_AREA_LENGTH_M = "additional_protected_area_length_m"
CONF_ADDITIONAL_PROTECTED_AREA_WIDTH_M = "additional_protected_area_width_m"
CONF_ADDITIONAL_PROTECTED_AREA_OFFSET_EAST_M = "additional_protected_area_offset_east_m"
CONF_ADDITIONAL_PROTECTED_AREA_OFFSET_NORTH_M = "additional_protected_area_offset_north_m"
CONF_HAS_SHADOW_CASTING_WALL = "has_shadow_casting_wall"
CONF_SHADOW_CASTING_WALL_LENGTH_M = "shadow_casting_wall_length_m"
CONF_SHADOW_CASTING_WALL_HEIGHT_M = "shadow_casting_wall_height_m"
CONF_SHADOW_CASTING_WALL_OFFSET_EAST_M = "shadow_casting_wall_offset_east_m"
CONF_SHADOW_CASTING_WALL_OFFSET_NORTH_M = "shadow_casting_wall_offset_north_m"

CONF_MAX_DIRECT_SUN_DEPTH_M = "max_direct_sun_depth_m"
CONF_OPEN_BEFORE_SUNRISE_MINUTES = "open_before_sunrise_minutes"
CONF_PREOPEN_ACTUATOR_PERCENT = "preopen_actuator_percent"

CONF_WIND_SPEED_SENSOR = "wind_speed_sensor"
CONF_RAIN_SENSOR = "rain_sensor"
CONF_IS_RAINING_SENSOR = "is_raining_sensor"
CONF_IS_WINDY_SENSOR = "is_windy_sensor"
CONF_SEVERE_SENSORS = "severe_sensors"
CONF_WIND_SPEED_THRESHOLD = "wind_speed_threshold"
CONF_RAIN_THRESHOLD = "rain_threshold"
CONF_WEATHER_OVERRIDE_POSITION = "weather_override_position"

DEFAULT_UPDATE_INTERVAL_SECONDS = 60
DEFAULT_COMMAND_EPSILON = 0.5
MANUAL_OVERRIDE_TOLERANCE_PERCENT = 3.0
MANUAL_OVERRIDE_WAIT_FOR_TARGET_SECONDS = 90

DEFAULT_NAME = "Adaptive Pergola"
DEFAULT_COMMAND_MODE = ACTUATOR_MODE_COVER_TILT
DEFAULT_COMMAND_VALUE_MIN = 0.0
DEFAULT_COMMAND_VALUE_MAX = 100.0
DEFAULT_AUTOMATIC_CONTROL = True
DEFAULT_AUTO_APPLY = True
DEFAULT_MANUAL_OVERRIDE_DURATION = {"hours": 2}
DEFAULT_MANUAL_OVERRIDE_RESET = False
DEFAULT_MANUAL_IGNORE_INTERMEDIATE = False
DEFAULT_TRACKING_MODE = TRACKING_BALANCED

DEFAULT_SLAT_WIDTH_M = 0.18
DEFAULT_SLAT_THICKNESS_M = 0.02
DEFAULT_SLAT_AXIS_SPACING_M = 0.20
DEFAULT_SLAT_AXIS_HEIGHT_M = 2.50
DEFAULT_PERGOLA_LENGTH_M = 4.00
DEFAULT_PERGOLA_WIDTH_M = 3.00
DEFAULT_AXIS_AZIMUTH_DEG = 0.0
DEFAULT_SLAT_AXIS_AZIMUTH_DEG = DEFAULT_AXIS_AZIMUTH_DEG
DEFAULT_PERGOLA_ORIENTATION_AZIMUTH_DEG = 90.0
DEFAULT_OPENING_AZIMUTH_DEG = DEFAULT_PERGOLA_ORIENTATION_AZIMUTH_DEG

DEFAULT_CLOSED_ANGLE_DEG = 0.0
DEFAULT_OPEN_ANGLE_DEG = 90.0
DEFAULT_MAX_TRAVEL_ANGLE_DEG = 135.0
DEFAULT_CLOSES_AGAIN_AFTER_OPEN = False

DEFAULT_HAS_HOUSE_ATTACHMENT = False
DEFAULT_HOUSE_HEIGHT_M = 3.00
DEFAULT_HOUSE_EXTENDS_LEFT_M = 0.0
DEFAULT_HOUSE_EXTENDS_RIGHT_M = 0.0

DEFAULT_HAS_ADDITIONAL_PROTECTED_AREA = False
DEFAULT_ADDITIONAL_PROTECTED_AREA_LENGTH_M = 0.0
DEFAULT_ADDITIONAL_PROTECTED_AREA_WIDTH_M = 0.0
DEFAULT_ADDITIONAL_PROTECTED_AREA_OFFSET_EAST_M = 0.0
DEFAULT_ADDITIONAL_PROTECTED_AREA_OFFSET_NORTH_M = 0.0
DEFAULT_HAS_SHADOW_CASTING_WALL = False
DEFAULT_SHADOW_CASTING_WALL_LENGTH_M = 0.0
DEFAULT_SHADOW_CASTING_WALL_HEIGHT_M = 0.0
DEFAULT_SHADOW_CASTING_WALL_OFFSET_EAST_M = 0.0
DEFAULT_SHADOW_CASTING_WALL_OFFSET_NORTH_M = 0.0

DEFAULT_MAX_DIRECT_SUN_DEPTH_M = 0.40
DEFAULT_OPEN_BEFORE_SUNRISE_MINUTES = 0
DEFAULT_PREOPEN_ACTUATOR_PERCENT = 0

DEFAULT_WIND_SPEED_THRESHOLD = 40.0
DEFAULT_RAIN_THRESHOLD = 0.8
DEFAULT_WEATHER_OVERRIDE_POSITION = 0
